name: dsd
description: "A new Flutter project for dsd company"

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  l: ^4.0.2
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  device_preview: ^1.1.0
  pinput: ^4.0.0

  smooth_page_indicator: ^1.1.0

  #for locale storage
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2

  #for network
  dio: ^5.4.1
  connectivity_plus: ^5.0.2
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0

  #for notification
  #  awesome_notifications: ^0.9.2

  #for state management
  flutter_riverpod: ^2.4.10

  #for rules
  dart_code_metrics: ^4.19.2

  #camera & image picker
  camera: 
  image_picker: ^1.0.7
  photo_manager: ^3.0.0
  searchfield: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/lang/
    - assets/icons/
    - assets/images/